
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-extensions
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 50Gi
  hostPath: 
    path: "/mnt/sonar/extensions/"
    type: DirectoryOrCreate